{
 "title": "Speed-Test for tv Copy",
 "tags": [
  "speedtest",
  "isp",
  "download",
  "upload"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "WAN IP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "WAN IP" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DOWNLOAD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "download" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "UPLOAD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "upload" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "Ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Testing against",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "Server Name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download ↓↓↓",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "download" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "In/Out Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "upload" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Speed Test" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "-1" ],
       "text": "scale(-1)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "download" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload ↑↑↑",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "upload" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping ms",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Speed Test" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SpeedTest" },
     "item": { "filter": "Ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}